# Generated by Django 6.0 on 2025-12-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('study', 'Study'), ('work', 'Work'), ('health', 'Health'), ('personal', 'Personal'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
