# Generated by Django 6.0 on 2025-12-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='creation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Task end time', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Task start time', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_date',
            field=models.DateField(blank=True, help_text='Date for the task', null=True),
        ),
    ]
