# Generated by Django 6.0 on 2026-04-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tasktemplateitem_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='focus_block_minutes',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_reminder_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_end_time',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
