# Generated by Django 6.0 on 2026-04-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tasktemplateitem_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='focus_duration',
            field=models.IntegerField(default=45, help_text='Focus block duration in minutes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_offset',
            field=models.IntegerField(default=15, help_text='Default reminder time in minutes before task'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
