# Generated by Django 6.0 on 2026-04-15 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Common name of the model', max_length=100, unique=True)),
                ('version', models.CharField(default='v1.0', max_length=50)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('offline', 'Offline')], default='healthy', max_length=20)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_suggestions', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'ML Model Config',
                'verbose_name_plural': 'ML Model Configs',
                'db_table': 'ml_model_configs',
            },
        ),
        migrations.CreateModel(
            name='MLInferenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='String representation of input context')),
                ('output_data', models.TextField(help_text='String representation of output prediction')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_inferences', to=settings.AUTH_USER_MODEL)),
                ('model_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inferences', to='api.mlmodelconfig')),
            ],
            options={
                'db_table': 'ml_inference_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MLErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='api.mlmodelconfig')),
            ],
            options={
                'db_table': 'ml_error_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
