# Generated by Django 6.0 on 2026-04-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_task_reminder_minutes_tasktemplateitem_reminder_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
